### ISSUE TITLE
[Develop] Rename Configuration entries renames other directories which start with the same name

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-extensions#103]
### Problem description
```
In [10]: Configuration.set('djef/test', 'test')

In [11]: list(client.prefix_entries('djef'))
Out[11]: [('djef/test', '"test"'), ('djef_test1', '"lol"')]

In [12]: Configuration.rename('djef', 'djef2')

In [13]: list(client.prefix_entries('djef'))
Out[13]: [('djef2/../djef_test1', '"lol"'), ('djef2/test', '"test"')]
```
Might be dangerous

**Comment by wimpers** [comment]
This is only used for 1 specific key atm (node ids which are being changed when updating)

**Comment by simonOpenV** [comment]
#### Should be fixed by:
https://github.com/openvstorage/framework-extensions/pull/161

https://github.com/openvstorage/framework/pull/2137

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework-extensions/releases/tag/0.5.0
