### ISSUE TITLE
Flask decorators should wrap API data in a dict instead of forcing the function to return a dict

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-extensions#122]

**Comment by simonOpenV** [comment]
Example:
```return {'targets': [t.export() for t in TargetList.get_targets()]}```
Is your point of the ticket that this should not be put in a dict manually and offloaded to the decorator? 
Problem:  not every API getter returns a dict. And does this ticket concern other calls as well?

**Comment by JeffreyDevloo** [comment]
It should always return {'data': INSERT DATA HERE} instead of customizing every response.

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework-extensions/releases/tag/0.5.0
