### ISSUE TITLE
API calls: standardize return values

### ISSUE THREAD

**Issue by simonOpenV** [openvstorage/framework-extensions#145]
Streamline return values of API calls by previously introduced decorator
Previously:
{<insert_key>:data}
starting from now:
{<insert_key: data, 'data': data}
the <insert_key> keys are only added for backwards compatibility.
Future work can leave this out.

**Comment by simonOpenV** [comment]
####API calls:
https://github.com/openvstorage/framework-extensions/pull/144
openvstorage-extensions-0.4.2-dev.1531748662.673950e
####Plugins:

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework-extensions/releases/tag/0.5.0
