### ISSUE TITLE
SSHClient cached instances are not thread safe

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-extensions#72]
### Problem description
Garbage collection could disconnect the current session for a certain SSHClient
This is mainly the case in using multithreaded SSHClient instances.
The current work around is to never create an SSHClient with a cached paramiko instance to avoid issues.

This should be looked after to avoid some other issues related to the SSHClient

EDIT: Could also serve as a constant reminder to not use cached instances with threads

**Comment by JeffreyDevloo** [comment]
https://github.com/openvstorage/framework-extensions/pull/74 might have helped a small bit. There is a now a reference counter so garbage collected threads would not destroy the underlying Paramiko instance

**Comment by simonOpenV** [comment]
### Fixed by
https://github.com/openvstorage/framework-extensions/pull/94

**Comment by JeffreyDevloo** [comment]
No, fixed by #74. Released in https://github.com/openvstorage/framework-extensions/releases/tag/0.1.2
